[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
fizzbuzz = "EFrtgjGmPdMkqJvQ57Z6PS1srtCTiaUreX6qtfY6UhFh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/invent2learn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
